//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.18444
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace PulseLeads.ConsoleTest.PulseLeadServiceClient {
    using System.Runtime.Serialization;
    using System;
    
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Runtime.Serialization", "4.0.0.0")]
    [System.Runtime.Serialization.DataContractAttribute(Name="PostLeadRequest", Namespace="http://schemas.datacontract.org/2004/07/FocusIT.Pulse")]
    [System.SerializableAttribute()]
    public partial class PostLeadRequest : object, System.Runtime.Serialization.IExtensibleDataObject, System.ComponentModel.INotifyPropertyChanged {
        
        [System.NonSerializedAttribute()]
        private System.Runtime.Serialization.ExtensionDataObject extensionDataField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private string BorrowerFirstNameField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private string BorrowerLastNameField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private string BorrowerMiddleNameField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private string BranchNameField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private string BusinessPhoneField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private string CellPhoneField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private bool CheckDuplicateField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private string CoBorrowerBusinessPhoneField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private string CoBorrowerCellPhoneField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private string CoBorrowerEmailField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private PulseLeads.ConsoleTest.PulseLeadServiceClient.Employment[] CoBorrowerEmployersField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private string CoBorrowerFirstNameField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private string CoBorrowerLastNameField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private string CoBorrowerMiddleNameField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private PulseLeads.ConsoleTest.PulseLeadServiceClient.OtherIncome[] CoBorrowerOtherIncomeField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private string CoBorrowerPhoneField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private string CoBorrowerTypeField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private string CountyField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private PulseLeads.ConsoleTest.PulseLeadServiceClient.CreditRanking CreditRankingField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private string DOBField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private string EmailField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private PulseLeads.ConsoleTest.PulseLeadServiceClient.Employment[] EmploymentField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private bool HaveDependentsField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private string HomePhoneField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private PulseLeads.ConsoleTest.PulseLeadServiceClient.Housing_Status HousingStatusField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private bool IncludeEscrowsField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private bool InterestOnlyField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private string LeadIdField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private string LeadSourceField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private PulseLeads.ConsoleTest.PulseLeadServiceClient.LiquidAssets[] LiquidAssetsField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private int LoanAmountField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private string LoanOfficerFirstNameField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private string LoanOfficerLastNameField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private string LoanProgramField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private string LoanTypeField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private PulseLeads.ConsoleTest.PulseLeadServiceClient.Address MailingAddressField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private decimal MonthlyPaymentField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private string NotesField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private PulseLeads.ConsoleTest.PulseLeadServiceClient.OccupancyType OccupancyTypeField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private PulseLeads.ConsoleTest.PulseLeadServiceClient.OtherIncome[] OtherIncomeField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private PulseLeads.ConsoleTest.PulseLeadServiceClient.PreferredContactMethod PreferredContactMethodField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private string PropertyTypeField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private int PropertyValueField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private string Property_CityField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private string Property_StateField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private string Property_StreetField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private string Property_ZipField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private PulseLeads.ConsoleTest.PulseLeadServiceClient.PurposeOfLoan PurposeOfLoanField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private decimal RateField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private int RentAmountField;
        
        private PulseLeads.ConsoleTest.PulseLeadServiceClient.ReqHdr RequestHeaderField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private string SSNField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private int TermField;
        
        [global::System.ComponentModel.BrowsableAttribute(false)]
        public System.Runtime.Serialization.ExtensionDataObject ExtensionData {
            get {
                return this.extensionDataField;
            }
            set {
                this.extensionDataField = value;
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public string BorrowerFirstName {
            get {
                return this.BorrowerFirstNameField;
            }
            set {
                if ((object.ReferenceEquals(this.BorrowerFirstNameField, value) != true)) {
                    this.BorrowerFirstNameField = value;
                    this.RaisePropertyChanged("BorrowerFirstName");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public string BorrowerLastName {
            get {
                return this.BorrowerLastNameField;
            }
            set {
                if ((object.ReferenceEquals(this.BorrowerLastNameField, value) != true)) {
                    this.BorrowerLastNameField = value;
                    this.RaisePropertyChanged("BorrowerLastName");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public string BorrowerMiddleName {
            get {
                return this.BorrowerMiddleNameField;
            }
            set {
                if ((object.ReferenceEquals(this.BorrowerMiddleNameField, value) != true)) {
                    this.BorrowerMiddleNameField = value;
                    this.RaisePropertyChanged("BorrowerMiddleName");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public string BranchName {
            get {
                return this.BranchNameField;
            }
            set {
                if ((object.ReferenceEquals(this.BranchNameField, value) != true)) {
                    this.BranchNameField = value;
                    this.RaisePropertyChanged("BranchName");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public string BusinessPhone {
            get {
                return this.BusinessPhoneField;
            }
            set {
                if ((object.ReferenceEquals(this.BusinessPhoneField, value) != true)) {
                    this.BusinessPhoneField = value;
                    this.RaisePropertyChanged("BusinessPhone");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public string CellPhone {
            get {
                return this.CellPhoneField;
            }
            set {
                if ((object.ReferenceEquals(this.CellPhoneField, value) != true)) {
                    this.CellPhoneField = value;
                    this.RaisePropertyChanged("CellPhone");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public bool CheckDuplicate {
            get {
                return this.CheckDuplicateField;
            }
            set {
                if ((this.CheckDuplicateField.Equals(value) != true)) {
                    this.CheckDuplicateField = value;
                    this.RaisePropertyChanged("CheckDuplicate");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public string CoBorrowerBusinessPhone {
            get {
                return this.CoBorrowerBusinessPhoneField;
            }
            set {
                if ((object.ReferenceEquals(this.CoBorrowerBusinessPhoneField, value) != true)) {
                    this.CoBorrowerBusinessPhoneField = value;
                    this.RaisePropertyChanged("CoBorrowerBusinessPhone");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public string CoBorrowerCellPhone {
            get {
                return this.CoBorrowerCellPhoneField;
            }
            set {
                if ((object.ReferenceEquals(this.CoBorrowerCellPhoneField, value) != true)) {
                    this.CoBorrowerCellPhoneField = value;
                    this.RaisePropertyChanged("CoBorrowerCellPhone");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public string CoBorrowerEmail {
            get {
                return this.CoBorrowerEmailField;
            }
            set {
                if ((object.ReferenceEquals(this.CoBorrowerEmailField, value) != true)) {
                    this.CoBorrowerEmailField = value;
                    this.RaisePropertyChanged("CoBorrowerEmail");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public PulseLeads.ConsoleTest.PulseLeadServiceClient.Employment[] CoBorrowerEmployers {
            get {
                return this.CoBorrowerEmployersField;
            }
            set {
                if ((object.ReferenceEquals(this.CoBorrowerEmployersField, value) != true)) {
                    this.CoBorrowerEmployersField = value;
                    this.RaisePropertyChanged("CoBorrowerEmployers");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public string CoBorrowerFirstName {
            get {
                return this.CoBorrowerFirstNameField;
            }
            set {
                if ((object.ReferenceEquals(this.CoBorrowerFirstNameField, value) != true)) {
                    this.CoBorrowerFirstNameField = value;
                    this.RaisePropertyChanged("CoBorrowerFirstName");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public string CoBorrowerLastName {
            get {
                return this.CoBorrowerLastNameField;
            }
            set {
                if ((object.ReferenceEquals(this.CoBorrowerLastNameField, value) != true)) {
                    this.CoBorrowerLastNameField = value;
                    this.RaisePropertyChanged("CoBorrowerLastName");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public string CoBorrowerMiddleName {
            get {
                return this.CoBorrowerMiddleNameField;
            }
            set {
                if ((object.ReferenceEquals(this.CoBorrowerMiddleNameField, value) != true)) {
                    this.CoBorrowerMiddleNameField = value;
                    this.RaisePropertyChanged("CoBorrowerMiddleName");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public PulseLeads.ConsoleTest.PulseLeadServiceClient.OtherIncome[] CoBorrowerOtherIncome {
            get {
                return this.CoBorrowerOtherIncomeField;
            }
            set {
                if ((object.ReferenceEquals(this.CoBorrowerOtherIncomeField, value) != true)) {
                    this.CoBorrowerOtherIncomeField = value;
                    this.RaisePropertyChanged("CoBorrowerOtherIncome");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public string CoBorrowerPhone {
            get {
                return this.CoBorrowerPhoneField;
            }
            set {
                if ((object.ReferenceEquals(this.CoBorrowerPhoneField, value) != true)) {
                    this.CoBorrowerPhoneField = value;
                    this.RaisePropertyChanged("CoBorrowerPhone");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public string CoBorrowerType {
            get {
                return this.CoBorrowerTypeField;
            }
            set {
                if ((object.ReferenceEquals(this.CoBorrowerTypeField, value) != true)) {
                    this.CoBorrowerTypeField = value;
                    this.RaisePropertyChanged("CoBorrowerType");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public string County {
            get {
                return this.CountyField;
            }
            set {
                if ((object.ReferenceEquals(this.CountyField, value) != true)) {
                    this.CountyField = value;
                    this.RaisePropertyChanged("County");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public PulseLeads.ConsoleTest.PulseLeadServiceClient.CreditRanking CreditRanking {
            get {
                return this.CreditRankingField;
            }
            set {
                if ((this.CreditRankingField.Equals(value) != true)) {
                    this.CreditRankingField = value;
                    this.RaisePropertyChanged("CreditRanking");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public string DOB {
            get {
                return this.DOBField;
            }
            set {
                if ((object.ReferenceEquals(this.DOBField, value) != true)) {
                    this.DOBField = value;
                    this.RaisePropertyChanged("DOB");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public string Email {
            get {
                return this.EmailField;
            }
            set {
                if ((object.ReferenceEquals(this.EmailField, value) != true)) {
                    this.EmailField = value;
                    this.RaisePropertyChanged("Email");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public PulseLeads.ConsoleTest.PulseLeadServiceClient.Employment[] Employment {
            get {
                return this.EmploymentField;
            }
            set {
                if ((object.ReferenceEquals(this.EmploymentField, value) != true)) {
                    this.EmploymentField = value;
                    this.RaisePropertyChanged("Employment");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public bool HaveDependents {
            get {
                return this.HaveDependentsField;
            }
            set {
                if ((this.HaveDependentsField.Equals(value) != true)) {
                    this.HaveDependentsField = value;
                    this.RaisePropertyChanged("HaveDependents");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public string HomePhone {
            get {
                return this.HomePhoneField;
            }
            set {
                if ((object.ReferenceEquals(this.HomePhoneField, value) != true)) {
                    this.HomePhoneField = value;
                    this.RaisePropertyChanged("HomePhone");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public PulseLeads.ConsoleTest.PulseLeadServiceClient.Housing_Status HousingStatus {
            get {
                return this.HousingStatusField;
            }
            set {
                if ((this.HousingStatusField.Equals(value) != true)) {
                    this.HousingStatusField = value;
                    this.RaisePropertyChanged("HousingStatus");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public bool IncludeEscrows {
            get {
                return this.IncludeEscrowsField;
            }
            set {
                if ((this.IncludeEscrowsField.Equals(value) != true)) {
                    this.IncludeEscrowsField = value;
                    this.RaisePropertyChanged("IncludeEscrows");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public bool InterestOnly {
            get {
                return this.InterestOnlyField;
            }
            set {
                if ((this.InterestOnlyField.Equals(value) != true)) {
                    this.InterestOnlyField = value;
                    this.RaisePropertyChanged("InterestOnly");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public string LeadId {
            get {
                return this.LeadIdField;
            }
            set {
                if ((object.ReferenceEquals(this.LeadIdField, value) != true)) {
                    this.LeadIdField = value;
                    this.RaisePropertyChanged("LeadId");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public string LeadSource {
            get {
                return this.LeadSourceField;
            }
            set {
                if ((object.ReferenceEquals(this.LeadSourceField, value) != true)) {
                    this.LeadSourceField = value;
                    this.RaisePropertyChanged("LeadSource");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public PulseLeads.ConsoleTest.PulseLeadServiceClient.LiquidAssets[] LiquidAssets {
            get {
                return this.LiquidAssetsField;
            }
            set {
                if ((object.ReferenceEquals(this.LiquidAssetsField, value) != true)) {
                    this.LiquidAssetsField = value;
                    this.RaisePropertyChanged("LiquidAssets");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public int LoanAmount {
            get {
                return this.LoanAmountField;
            }
            set {
                if ((this.LoanAmountField.Equals(value) != true)) {
                    this.LoanAmountField = value;
                    this.RaisePropertyChanged("LoanAmount");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public string LoanOfficerFirstName {
            get {
                return this.LoanOfficerFirstNameField;
            }
            set {
                if ((object.ReferenceEquals(this.LoanOfficerFirstNameField, value) != true)) {
                    this.LoanOfficerFirstNameField = value;
                    this.RaisePropertyChanged("LoanOfficerFirstName");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public string LoanOfficerLastName {
            get {
                return this.LoanOfficerLastNameField;
            }
            set {
                if ((object.ReferenceEquals(this.LoanOfficerLastNameField, value) != true)) {
                    this.LoanOfficerLastNameField = value;
                    this.RaisePropertyChanged("LoanOfficerLastName");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public string LoanProgram {
            get {
                return this.LoanProgramField;
            }
            set {
                if ((object.ReferenceEquals(this.LoanProgramField, value) != true)) {
                    this.LoanProgramField = value;
                    this.RaisePropertyChanged("LoanProgram");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public string LoanType {
            get {
                return this.LoanTypeField;
            }
            set {
                if ((object.ReferenceEquals(this.LoanTypeField, value) != true)) {
                    this.LoanTypeField = value;
                    this.RaisePropertyChanged("LoanType");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public PulseLeads.ConsoleTest.PulseLeadServiceClient.Address MailingAddress {
            get {
                return this.MailingAddressField;
            }
            set {
                if ((object.ReferenceEquals(this.MailingAddressField, value) != true)) {
                    this.MailingAddressField = value;
                    this.RaisePropertyChanged("MailingAddress");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public decimal MonthlyPayment {
            get {
                return this.MonthlyPaymentField;
            }
            set {
                if ((this.MonthlyPaymentField.Equals(value) != true)) {
                    this.MonthlyPaymentField = value;
                    this.RaisePropertyChanged("MonthlyPayment");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public string Notes {
            get {
                return this.NotesField;
            }
            set {
                if ((object.ReferenceEquals(this.NotesField, value) != true)) {
                    this.NotesField = value;
                    this.RaisePropertyChanged("Notes");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public PulseLeads.ConsoleTest.PulseLeadServiceClient.OccupancyType OccupancyType {
            get {
                return this.OccupancyTypeField;
            }
            set {
                if ((this.OccupancyTypeField.Equals(value) != true)) {
                    this.OccupancyTypeField = value;
                    this.RaisePropertyChanged("OccupancyType");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public PulseLeads.ConsoleTest.PulseLeadServiceClient.OtherIncome[] OtherIncome {
            get {
                return this.OtherIncomeField;
            }
            set {
                if ((object.ReferenceEquals(this.OtherIncomeField, value) != true)) {
                    this.OtherIncomeField = value;
                    this.RaisePropertyChanged("OtherIncome");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public PulseLeads.ConsoleTest.PulseLeadServiceClient.PreferredContactMethod PreferredContactMethod {
            get {
                return this.PreferredContactMethodField;
            }
            set {
                if ((this.PreferredContactMethodField.Equals(value) != true)) {
                    this.PreferredContactMethodField = value;
                    this.RaisePropertyChanged("PreferredContactMethod");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public string PropertyType {
            get {
                return this.PropertyTypeField;
            }
            set {
                if ((object.ReferenceEquals(this.PropertyTypeField, value) != true)) {
                    this.PropertyTypeField = value;
                    this.RaisePropertyChanged("PropertyType");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public int PropertyValue {
            get {
                return this.PropertyValueField;
            }
            set {
                if ((this.PropertyValueField.Equals(value) != true)) {
                    this.PropertyValueField = value;
                    this.RaisePropertyChanged("PropertyValue");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public string Property_City {
            get {
                return this.Property_CityField;
            }
            set {
                if ((object.ReferenceEquals(this.Property_CityField, value) != true)) {
                    this.Property_CityField = value;
                    this.RaisePropertyChanged("Property_City");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public string Property_State {
            get {
                return this.Property_StateField;
            }
            set {
                if ((object.ReferenceEquals(this.Property_StateField, value) != true)) {
                    this.Property_StateField = value;
                    this.RaisePropertyChanged("Property_State");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public string Property_Street {
            get {
                return this.Property_StreetField;
            }
            set {
                if ((object.ReferenceEquals(this.Property_StreetField, value) != true)) {
                    this.Property_StreetField = value;
                    this.RaisePropertyChanged("Property_Street");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public string Property_Zip {
            get {
                return this.Property_ZipField;
            }
            set {
                if ((object.ReferenceEquals(this.Property_ZipField, value) != true)) {
                    this.Property_ZipField = value;
                    this.RaisePropertyChanged("Property_Zip");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public PulseLeads.ConsoleTest.PulseLeadServiceClient.PurposeOfLoan PurposeOfLoan {
            get {
                return this.PurposeOfLoanField;
            }
            set {
                if ((this.PurposeOfLoanField.Equals(value) != true)) {
                    this.PurposeOfLoanField = value;
                    this.RaisePropertyChanged("PurposeOfLoan");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public decimal Rate {
            get {
                return this.RateField;
            }
            set {
                if ((this.RateField.Equals(value) != true)) {
                    this.RateField = value;
                    this.RaisePropertyChanged("Rate");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public int RentAmount {
            get {
                return this.RentAmountField;
            }
            set {
                if ((this.RentAmountField.Equals(value) != true)) {
                    this.RentAmountField = value;
                    this.RaisePropertyChanged("RentAmount");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute(IsRequired=true)]
        public PulseLeads.ConsoleTest.PulseLeadServiceClient.ReqHdr RequestHeader {
            get {
                return this.RequestHeaderField;
            }
            set {
                if ((object.ReferenceEquals(this.RequestHeaderField, value) != true)) {
                    this.RequestHeaderField = value;
                    this.RaisePropertyChanged("RequestHeader");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public string SSN {
            get {
                return this.SSNField;
            }
            set {
                if ((object.ReferenceEquals(this.SSNField, value) != true)) {
                    this.SSNField = value;
                    this.RaisePropertyChanged("SSN");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public int Term {
            get {
                return this.TermField;
            }
            set {
                if ((this.TermField.Equals(value) != true)) {
                    this.TermField = value;
                    this.RaisePropertyChanged("Term");
                }
            }
        }
        
        public event System.ComponentModel.PropertyChangedEventHandler PropertyChanged;
        
        protected void RaisePropertyChanged(string propertyName) {
            System.ComponentModel.PropertyChangedEventHandler propertyChanged = this.PropertyChanged;
            if ((propertyChanged != null)) {
                propertyChanged(this, new System.ComponentModel.PropertyChangedEventArgs(propertyName));
            }
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Runtime.Serialization", "4.0.0.0")]
    [System.Runtime.Serialization.DataContractAttribute(Name="Address", Namespace="http://schemas.datacontract.org/2004/07/FocusIT.Pulse")]
    [System.SerializableAttribute()]
    public partial class Address : object, System.Runtime.Serialization.IExtensibleDataObject, System.ComponentModel.INotifyPropertyChanged {
        
        [System.NonSerializedAttribute()]
        private System.Runtime.Serialization.ExtensionDataObject extensionDataField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private string CityField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private string StateField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private string StreetField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private string ZipField;
        
        [global::System.ComponentModel.BrowsableAttribute(false)]
        public System.Runtime.Serialization.ExtensionDataObject ExtensionData {
            get {
                return this.extensionDataField;
            }
            set {
                this.extensionDataField = value;
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public string City {
            get {
                return this.CityField;
            }
            set {
                if ((object.ReferenceEquals(this.CityField, value) != true)) {
                    this.CityField = value;
                    this.RaisePropertyChanged("City");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public string State {
            get {
                return this.StateField;
            }
            set {
                if ((object.ReferenceEquals(this.StateField, value) != true)) {
                    this.StateField = value;
                    this.RaisePropertyChanged("State");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public string Street {
            get {
                return this.StreetField;
            }
            set {
                if ((object.ReferenceEquals(this.StreetField, value) != true)) {
                    this.StreetField = value;
                    this.RaisePropertyChanged("Street");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public string Zip {
            get {
                return this.ZipField;
            }
            set {
                if ((object.ReferenceEquals(this.ZipField, value) != true)) {
                    this.ZipField = value;
                    this.RaisePropertyChanged("Zip");
                }
            }
        }
        
        public event System.ComponentModel.PropertyChangedEventHandler PropertyChanged;
        
        protected void RaisePropertyChanged(string propertyName) {
            System.ComponentModel.PropertyChangedEventHandler propertyChanged = this.PropertyChanged;
            if ((propertyChanged != null)) {
                propertyChanged(this, new System.ComponentModel.PropertyChangedEventArgs(propertyName));
            }
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Runtime.Serialization", "4.0.0.0")]
    [System.Runtime.Serialization.DataContractAttribute(Name="ReqHdr", Namespace="http://schemas.datacontract.org/2004/07/FocusIT.Pulse")]
    [System.SerializableAttribute()]
    public partial class ReqHdr : object, System.Runtime.Serialization.IExtensibleDataObject, System.ComponentModel.INotifyPropertyChanged {
        
        [System.NonSerializedAttribute()]
        private System.Runtime.Serialization.ExtensionDataObject extensionDataField;
        
        private string SecurityTokenField;
        
        [global::System.ComponentModel.BrowsableAttribute(false)]
        public System.Runtime.Serialization.ExtensionDataObject ExtensionData {
            get {
                return this.extensionDataField;
            }
            set {
                this.extensionDataField = value;
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute(IsRequired=true)]
        public string SecurityToken {
            get {
                return this.SecurityTokenField;
            }
            set {
                if ((object.ReferenceEquals(this.SecurityTokenField, value) != true)) {
                    this.SecurityTokenField = value;
                    this.RaisePropertyChanged("SecurityToken");
                }
            }
        }
        
        public event System.ComponentModel.PropertyChangedEventHandler PropertyChanged;
        
        protected void RaisePropertyChanged(string propertyName) {
            System.ComponentModel.PropertyChangedEventHandler propertyChanged = this.PropertyChanged;
            if ((propertyChanged != null)) {
                propertyChanged(this, new System.ComponentModel.PropertyChangedEventArgs(propertyName));
            }
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Runtime.Serialization", "4.0.0.0")]
    [System.Runtime.Serialization.DataContractAttribute(Name="Employment", Namespace="http://schemas.datacontract.org/2004/07/FocusIT.Pulse")]
    [System.SerializableAttribute()]
    public partial class Employment : object, System.Runtime.Serialization.IExtensibleDataObject, System.ComponentModel.INotifyPropertyChanged {
        
        [System.NonSerializedAttribute()]
        private System.Runtime.Serialization.ExtensionDataObject extensionDataField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private PulseLeads.ConsoleTest.PulseLeadServiceClient.Address AddressField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private string BusinessTypeField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private string CompanyField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private int EndMonthField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private int EndYearField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private decimal MonthlySalaryField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private int MonthsInProfessionField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private string PhoneField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private string PositionField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private bool SelfEmployedField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private int StartMonthField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private int StartYearField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private bool VerifyYourTaxesField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private int YearsInProfessionField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private int YearsOnWorkField;
        
        [global::System.ComponentModel.BrowsableAttribute(false)]
        public System.Runtime.Serialization.ExtensionDataObject ExtensionData {
            get {
                return this.extensionDataField;
            }
            set {
                this.extensionDataField = value;
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public PulseLeads.ConsoleTest.PulseLeadServiceClient.Address Address {
            get {
                return this.AddressField;
            }
            set {
                if ((object.ReferenceEquals(this.AddressField, value) != true)) {
                    this.AddressField = value;
                    this.RaisePropertyChanged("Address");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public string BusinessType {
            get {
                return this.BusinessTypeField;
            }
            set {
                if ((object.ReferenceEquals(this.BusinessTypeField, value) != true)) {
                    this.BusinessTypeField = value;
                    this.RaisePropertyChanged("BusinessType");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public string Company {
            get {
                return this.CompanyField;
            }
            set {
                if ((object.ReferenceEquals(this.CompanyField, value) != true)) {
                    this.CompanyField = value;
                    this.RaisePropertyChanged("Company");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public int EndMonth {
            get {
                return this.EndMonthField;
            }
            set {
                if ((this.EndMonthField.Equals(value) != true)) {
                    this.EndMonthField = value;
                    this.RaisePropertyChanged("EndMonth");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public int EndYear {
            get {
                return this.EndYearField;
            }
            set {
                if ((this.EndYearField.Equals(value) != true)) {
                    this.EndYearField = value;
                    this.RaisePropertyChanged("EndYear");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public decimal MonthlySalary {
            get {
                return this.MonthlySalaryField;
            }
            set {
                if ((this.MonthlySalaryField.Equals(value) != true)) {
                    this.MonthlySalaryField = value;
                    this.RaisePropertyChanged("MonthlySalary");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public int MonthsInProfession {
            get {
                return this.MonthsInProfessionField;
            }
            set {
                if ((this.MonthsInProfessionField.Equals(value) != true)) {
                    this.MonthsInProfessionField = value;
                    this.RaisePropertyChanged("MonthsInProfession");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public string Phone {
            get {
                return this.PhoneField;
            }
            set {
                if ((object.ReferenceEquals(this.PhoneField, value) != true)) {
                    this.PhoneField = value;
                    this.RaisePropertyChanged("Phone");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public string Position {
            get {
                return this.PositionField;
            }
            set {
                if ((object.ReferenceEquals(this.PositionField, value) != true)) {
                    this.PositionField = value;
                    this.RaisePropertyChanged("Position");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public bool SelfEmployed {
            get {
                return this.SelfEmployedField;
            }
            set {
                if ((this.SelfEmployedField.Equals(value) != true)) {
                    this.SelfEmployedField = value;
                    this.RaisePropertyChanged("SelfEmployed");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public int StartMonth {
            get {
                return this.StartMonthField;
            }
            set {
                if ((this.StartMonthField.Equals(value) != true)) {
                    this.StartMonthField = value;
                    this.RaisePropertyChanged("StartMonth");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public int StartYear {
            get {
                return this.StartYearField;
            }
            set {
                if ((this.StartYearField.Equals(value) != true)) {
                    this.StartYearField = value;
                    this.RaisePropertyChanged("StartYear");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public bool VerifyYourTaxes {
            get {
                return this.VerifyYourTaxesField;
            }
            set {
                if ((this.VerifyYourTaxesField.Equals(value) != true)) {
                    this.VerifyYourTaxesField = value;
                    this.RaisePropertyChanged("VerifyYourTaxes");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public int YearsInProfession {
            get {
                return this.YearsInProfessionField;
            }
            set {
                if ((this.YearsInProfessionField.Equals(value) != true)) {
                    this.YearsInProfessionField = value;
                    this.RaisePropertyChanged("YearsInProfession");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public int YearsOnWork {
            get {
                return this.YearsOnWorkField;
            }
            set {
                if ((this.YearsOnWorkField.Equals(value) != true)) {
                    this.YearsOnWorkField = value;
                    this.RaisePropertyChanged("YearsOnWork");
                }
            }
        }
        
        public event System.ComponentModel.PropertyChangedEventHandler PropertyChanged;
        
        protected void RaisePropertyChanged(string propertyName) {
            System.ComponentModel.PropertyChangedEventHandler propertyChanged = this.PropertyChanged;
            if ((propertyChanged != null)) {
                propertyChanged(this, new System.ComponentModel.PropertyChangedEventArgs(propertyName));
            }
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Runtime.Serialization", "4.0.0.0")]
    [System.Runtime.Serialization.DataContractAttribute(Name="OtherIncome", Namespace="http://schemas.datacontract.org/2004/07/FocusIT.Pulse")]
    [System.SerializableAttribute()]
    public partial class OtherIncome : object, System.Runtime.Serialization.IExtensibleDataObject, System.ComponentModel.INotifyPropertyChanged {
        
        [System.NonSerializedAttribute()]
        private System.Runtime.Serialization.ExtensionDataObject extensionDataField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private decimal AmountField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private string TypeField;
        
        [global::System.ComponentModel.BrowsableAttribute(false)]
        public System.Runtime.Serialization.ExtensionDataObject ExtensionData {
            get {
                return this.extensionDataField;
            }
            set {
                this.extensionDataField = value;
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public decimal Amount {
            get {
                return this.AmountField;
            }
            set {
                if ((this.AmountField.Equals(value) != true)) {
                    this.AmountField = value;
                    this.RaisePropertyChanged("Amount");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public string Type {
            get {
                return this.TypeField;
            }
            set {
                if ((object.ReferenceEquals(this.TypeField, value) != true)) {
                    this.TypeField = value;
                    this.RaisePropertyChanged("Type");
                }
            }
        }
        
        public event System.ComponentModel.PropertyChangedEventHandler PropertyChanged;
        
        protected void RaisePropertyChanged(string propertyName) {
            System.ComponentModel.PropertyChangedEventHandler propertyChanged = this.PropertyChanged;
            if ((propertyChanged != null)) {
                propertyChanged(this, new System.ComponentModel.PropertyChangedEventArgs(propertyName));
            }
        }
    }
    
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Runtime.Serialization", "4.0.0.0")]
    [System.Runtime.Serialization.DataContractAttribute(Name="CreditRanking", Namespace="http://schemas.datacontract.org/2004/07/FocusIT.Pulse")]
    public enum CreditRanking : int {
        
        [System.Runtime.Serialization.EnumMemberAttribute()]
        Excellent = 1,
        
        [System.Runtime.Serialization.EnumMemberAttribute()]
        VeryGood = 2,
        
        [System.Runtime.Serialization.EnumMemberAttribute()]
        Good = 3,
        
        [System.Runtime.Serialization.EnumMemberAttribute()]
        Fair = 4,
        
        [System.Runtime.Serialization.EnumMemberAttribute()]
        Poor = 5,
    }
    
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Runtime.Serialization", "4.0.0.0")]
    [System.Runtime.Serialization.DataContractAttribute(Name="Housing_Status", Namespace="http://schemas.datacontract.org/2004/07/FocusIT.Pulse")]
    public enum Housing_Status : int {
        
        [System.Runtime.Serialization.EnumMemberAttribute()]
        Own = 0,
        
        [System.Runtime.Serialization.EnumMemberAttribute()]
        Rent = 1,
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Runtime.Serialization", "4.0.0.0")]
    [System.Runtime.Serialization.DataContractAttribute(Name="LiquidAssets", Namespace="http://schemas.datacontract.org/2004/07/FocusIT.Pulse")]
    [System.SerializableAttribute()]
    public partial class LiquidAssets : object, System.Runtime.Serialization.IExtensibleDataObject, System.ComponentModel.INotifyPropertyChanged {
        
        [System.NonSerializedAttribute()]
        private System.Runtime.Serialization.ExtensionDataObject extensionDataField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private string AccountNoField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private decimal AmountField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private string NameOfAccountField;
        
        [global::System.ComponentModel.BrowsableAttribute(false)]
        public System.Runtime.Serialization.ExtensionDataObject ExtensionData {
            get {
                return this.extensionDataField;
            }
            set {
                this.extensionDataField = value;
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public string AccountNo {
            get {
                return this.AccountNoField;
            }
            set {
                if ((object.ReferenceEquals(this.AccountNoField, value) != true)) {
                    this.AccountNoField = value;
                    this.RaisePropertyChanged("AccountNo");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public decimal Amount {
            get {
                return this.AmountField;
            }
            set {
                if ((this.AmountField.Equals(value) != true)) {
                    this.AmountField = value;
                    this.RaisePropertyChanged("Amount");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public string NameOfAccount {
            get {
                return this.NameOfAccountField;
            }
            set {
                if ((object.ReferenceEquals(this.NameOfAccountField, value) != true)) {
                    this.NameOfAccountField = value;
                    this.RaisePropertyChanged("NameOfAccount");
                }
            }
        }
        
        public event System.ComponentModel.PropertyChangedEventHandler PropertyChanged;
        
        protected void RaisePropertyChanged(string propertyName) {
            System.ComponentModel.PropertyChangedEventHandler propertyChanged = this.PropertyChanged;
            if ((propertyChanged != null)) {
                propertyChanged(this, new System.ComponentModel.PropertyChangedEventArgs(propertyName));
            }
        }
    }
    
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Runtime.Serialization", "4.0.0.0")]
    [System.Runtime.Serialization.DataContractAttribute(Name="OccupancyType", Namespace="http://schemas.datacontract.org/2004/07/FocusIT.Pulse")]
    public enum OccupancyType : int {
        
        [System.Runtime.Serialization.EnumMemberAttribute()]
        PrimaryResidence = 1,
        
        [System.Runtime.Serialization.EnumMemberAttribute()]
        SecondHome = 2,
        
        [System.Runtime.Serialization.EnumMemberAttribute()]
        InvestmentProperty = 3,
    }
    
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Runtime.Serialization", "4.0.0.0")]
    [System.Runtime.Serialization.DataContractAttribute(Name="PreferredContactMethod", Namespace="http://schemas.datacontract.org/2004/07/FocusIT.Pulse")]
    public enum PreferredContactMethod : int {
        
        [System.Runtime.Serialization.EnumMemberAttribute()]
        HomePhone = 1,
        
        [System.Runtime.Serialization.EnumMemberAttribute()]
        BusinessPhone = 2,
        
        [System.Runtime.Serialization.EnumMemberAttribute()]
        CellPhone = 3,
        
        [System.Runtime.Serialization.EnumMemberAttribute()]
        Email = 4,
    }
    
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Runtime.Serialization", "4.0.0.0")]
    [System.Runtime.Serialization.DataContractAttribute(Name="PurposeOfLoan", Namespace="http://schemas.datacontract.org/2004/07/FocusIT.Pulse")]
    public enum PurposeOfLoan : int {
        
        [System.Runtime.Serialization.EnumMemberAttribute()]
        Purchase = 1,
        
        [System.Runtime.Serialization.EnumMemberAttribute()]
        Refinance_No_Cashout = 2,
        
        [System.Runtime.Serialization.EnumMemberAttribute()]
        Refinance_Cashout = 3,
        
        [System.Runtime.Serialization.EnumMemberAttribute()]
        Construction = 4,
        
        [System.Runtime.Serialization.EnumMemberAttribute()]
        Other = 5,
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Runtime.Serialization", "4.0.0.0")]
    [System.Runtime.Serialization.DataContractAttribute(Name="RespHdr", Namespace="http://schemas.datacontract.org/2004/07/FocusIT.Pulse")]
    [System.SerializableAttribute()]
    public partial class RespHdr : object, System.Runtime.Serialization.IExtensibleDataObject, System.ComponentModel.INotifyPropertyChanged {
        
        [System.NonSerializedAttribute()]
        private System.Runtime.Serialization.ExtensionDataObject extensionDataField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private string ErrorField;
        
        private bool SuccessfulField;
        
        [global::System.ComponentModel.BrowsableAttribute(false)]
        public System.Runtime.Serialization.ExtensionDataObject ExtensionData {
            get {
                return this.extensionDataField;
            }
            set {
                this.extensionDataField = value;
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public string Error {
            get {
                return this.ErrorField;
            }
            set {
                if ((object.ReferenceEquals(this.ErrorField, value) != true)) {
                    this.ErrorField = value;
                    this.RaisePropertyChanged("Error");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute(IsRequired=true)]
        public bool Successful {
            get {
                return this.SuccessfulField;
            }
            set {
                if ((this.SuccessfulField.Equals(value) != true)) {
                    this.SuccessfulField = value;
                    this.RaisePropertyChanged("Successful");
                }
            }
        }
        
        public event System.ComponentModel.PropertyChangedEventHandler PropertyChanged;
        
        protected void RaisePropertyChanged(string propertyName) {
            System.ComponentModel.PropertyChangedEventHandler propertyChanged = this.PropertyChanged;
            if ((propertyChanged != null)) {
                propertyChanged(this, new System.ComponentModel.PropertyChangedEventArgs(propertyName));
            }
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Runtime.Serialization", "4.0.0.0")]
    [System.Runtime.Serialization.DataContractAttribute(Name="PostLoanAppRequest", Namespace="http://schemas.datacontract.org/2004/07/FocusIT.Pulse")]
    [System.SerializableAttribute()]
    public partial class PostLoanAppRequest : object, System.Runtime.Serialization.IExtensibleDataObject, System.ComponentModel.INotifyPropertyChanged {
        
        [System.NonSerializedAttribute()]
        private System.Runtime.Serialization.ExtensionDataObject extensionDataField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private string BorrowerFirstNameField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private string BorrowerLastNameField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private string BorrowerMiddleNameField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private string BranchNameField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private string BusinessPhoneField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private string CellPhoneField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private bool CheckDuplicateField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private string CoBorrowerBusinessPhoneField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private string CoBorrowerCellPhoneField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private string CoBorrowerEmailField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private PulseLeads.ConsoleTest.PulseLeadServiceClient.Employment[] CoBorrowerEmployersField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private string CoBorrowerFirstNameField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private string CoBorrowerLastNameField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private string CoBorrowerMiddleNameField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private PulseLeads.ConsoleTest.PulseLeadServiceClient.OtherIncome[] CoBorrowerOtherIncomeField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private string CoBorrowerPhoneField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private string CoBorrowerTypeField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private string CountyField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private PulseLeads.ConsoleTest.PulseLeadServiceClient.CreditRanking CreditRankingField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private string DOBField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private string EmailField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private PulseLeads.ConsoleTest.PulseLeadServiceClient.Employment[] EmploymentField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private bool HaveDependentsField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private string HomePhoneField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private PulseLeads.ConsoleTest.PulseLeadServiceClient.Housing_Status HousingStatusField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private bool IncludeEscrowsField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private bool InterestOnlyField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private string LeadIdField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private string LeadSourceField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private PulseLeads.ConsoleTest.PulseLeadServiceClient.LiquidAssets[] LiquidAssetsField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private int LoanAmountField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private string LoanOfficerFirstNameField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private string LoanOfficerLastNameField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private string LoanProgramField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private string LoanTypeField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private PulseLeads.ConsoleTest.PulseLeadServiceClient.Address MailingAddressField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private decimal MonthlyPaymentField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private string NotesField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private PulseLeads.ConsoleTest.PulseLeadServiceClient.OccupancyType OccupancyTypeField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private PulseLeads.ConsoleTest.PulseLeadServiceClient.OtherIncome[] OtherIncomeField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private PulseLeads.ConsoleTest.PulseLeadServiceClient.PreferredContactMethod PreferredContactMethodField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private PulseLeads.ConsoleTest.PulseLeadServiceClient.Address PropertyField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private string PropertyTypeField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private int PropertyValueField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private PulseLeads.ConsoleTest.PulseLeadServiceClient.PurposeOfLoan PurposeOfLoanField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private decimal RateField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private int RentAmountField;
        
        private PulseLeads.ConsoleTest.PulseLeadServiceClient.ReqHdr RequestHeaderField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private string SSNField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private int TermField;
        
        [global::System.ComponentModel.BrowsableAttribute(false)]
        public System.Runtime.Serialization.ExtensionDataObject ExtensionData {
            get {
                return this.extensionDataField;
            }
            set {
                this.extensionDataField = value;
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public string BorrowerFirstName {
            get {
                return this.BorrowerFirstNameField;
            }
            set {
                if ((object.ReferenceEquals(this.BorrowerFirstNameField, value) != true)) {
                    this.BorrowerFirstNameField = value;
                    this.RaisePropertyChanged("BorrowerFirstName");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public string BorrowerLastName {
            get {
                return this.BorrowerLastNameField;
            }
            set {
                if ((object.ReferenceEquals(this.BorrowerLastNameField, value) != true)) {
                    this.BorrowerLastNameField = value;
                    this.RaisePropertyChanged("BorrowerLastName");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public string BorrowerMiddleName {
            get {
                return this.BorrowerMiddleNameField;
            }
            set {
                if ((object.ReferenceEquals(this.BorrowerMiddleNameField, value) != true)) {
                    this.BorrowerMiddleNameField = value;
                    this.RaisePropertyChanged("BorrowerMiddleName");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public string BranchName {
            get {
                return this.BranchNameField;
            }
            set {
                if ((object.ReferenceEquals(this.BranchNameField, value) != true)) {
                    this.BranchNameField = value;
                    this.RaisePropertyChanged("BranchName");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public string BusinessPhone {
            get {
                return this.BusinessPhoneField;
            }
            set {
                if ((object.ReferenceEquals(this.BusinessPhoneField, value) != true)) {
                    this.BusinessPhoneField = value;
                    this.RaisePropertyChanged("BusinessPhone");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public string CellPhone {
            get {
                return this.CellPhoneField;
            }
            set {
                if ((object.ReferenceEquals(this.CellPhoneField, value) != true)) {
                    this.CellPhoneField = value;
                    this.RaisePropertyChanged("CellPhone");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public bool CheckDuplicate {
            get {
                return this.CheckDuplicateField;
            }
            set {
                if ((this.CheckDuplicateField.Equals(value) != true)) {
                    this.CheckDuplicateField = value;
                    this.RaisePropertyChanged("CheckDuplicate");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public string CoBorrowerBusinessPhone {
            get {
                return this.CoBorrowerBusinessPhoneField;
            }
            set {
                if ((object.ReferenceEquals(this.CoBorrowerBusinessPhoneField, value) != true)) {
                    this.CoBorrowerBusinessPhoneField = value;
                    this.RaisePropertyChanged("CoBorrowerBusinessPhone");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public string CoBorrowerCellPhone {
            get {
                return this.CoBorrowerCellPhoneField;
            }
            set {
                if ((object.ReferenceEquals(this.CoBorrowerCellPhoneField, value) != true)) {
                    this.CoBorrowerCellPhoneField = value;
                    this.RaisePropertyChanged("CoBorrowerCellPhone");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public string CoBorrowerEmail {
            get {
                return this.CoBorrowerEmailField;
            }
            set {
                if ((object.ReferenceEquals(this.CoBorrowerEmailField, value) != true)) {
                    this.CoBorrowerEmailField = value;
                    this.RaisePropertyChanged("CoBorrowerEmail");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public PulseLeads.ConsoleTest.PulseLeadServiceClient.Employment[] CoBorrowerEmployers {
            get {
                return this.CoBorrowerEmployersField;
            }
            set {
                if ((object.ReferenceEquals(this.CoBorrowerEmployersField, value) != true)) {
                    this.CoBorrowerEmployersField = value;
                    this.RaisePropertyChanged("CoBorrowerEmployers");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public string CoBorrowerFirstName {
            get {
                return this.CoBorrowerFirstNameField;
            }
            set {
                if ((object.ReferenceEquals(this.CoBorrowerFirstNameField, value) != true)) {
                    this.CoBorrowerFirstNameField = value;
                    this.RaisePropertyChanged("CoBorrowerFirstName");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public string CoBorrowerLastName {
            get {
                return this.CoBorrowerLastNameField;
            }
            set {
                if ((object.ReferenceEquals(this.CoBorrowerLastNameField, value) != true)) {
                    this.CoBorrowerLastNameField = value;
                    this.RaisePropertyChanged("CoBorrowerLastName");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public string CoBorrowerMiddleName {
            get {
                return this.CoBorrowerMiddleNameField;
            }
            set {
                if ((object.ReferenceEquals(this.CoBorrowerMiddleNameField, value) != true)) {
                    this.CoBorrowerMiddleNameField = value;
                    this.RaisePropertyChanged("CoBorrowerMiddleName");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public PulseLeads.ConsoleTest.PulseLeadServiceClient.OtherIncome[] CoBorrowerOtherIncome {
            get {
                return this.CoBorrowerOtherIncomeField;
            }
            set {
                if ((object.ReferenceEquals(this.CoBorrowerOtherIncomeField, value) != true)) {
                    this.CoBorrowerOtherIncomeField = value;
                    this.RaisePropertyChanged("CoBorrowerOtherIncome");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public string CoBorrowerPhone {
            get {
                return this.CoBorrowerPhoneField;
            }
            set {
                if ((object.ReferenceEquals(this.CoBorrowerPhoneField, value) != true)) {
                    this.CoBorrowerPhoneField = value;
                    this.RaisePropertyChanged("CoBorrowerPhone");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public string CoBorrowerType {
            get {
                return this.CoBorrowerTypeField;
            }
            set {
                if ((object.ReferenceEquals(this.CoBorrowerTypeField, value) != true)) {
                    this.CoBorrowerTypeField = value;
                    this.RaisePropertyChanged("CoBorrowerType");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public string County {
            get {
                return this.CountyField;
            }
            set {
                if ((object.ReferenceEquals(this.CountyField, value) != true)) {
                    this.CountyField = value;
                    this.RaisePropertyChanged("County");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public PulseLeads.ConsoleTest.PulseLeadServiceClient.CreditRanking CreditRanking {
            get {
                return this.CreditRankingField;
            }
            set {
                if ((this.CreditRankingField.Equals(value) != true)) {
                    this.CreditRankingField = value;
                    this.RaisePropertyChanged("CreditRanking");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public string DOB {
            get {
                return this.DOBField;
            }
            set {
                if ((object.ReferenceEquals(this.DOBField, value) != true)) {
                    this.DOBField = value;
                    this.RaisePropertyChanged("DOB");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public string Email {
            get {
                return this.EmailField;
            }
            set {
                if ((object.ReferenceEquals(this.EmailField, value) != true)) {
                    this.EmailField = value;
                    this.RaisePropertyChanged("Email");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public PulseLeads.ConsoleTest.PulseLeadServiceClient.Employment[] Employment {
            get {
                return this.EmploymentField;
            }
            set {
                if ((object.ReferenceEquals(this.EmploymentField, value) != true)) {
                    this.EmploymentField = value;
                    this.RaisePropertyChanged("Employment");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public bool HaveDependents {
            get {
                return this.HaveDependentsField;
            }
            set {
                if ((this.HaveDependentsField.Equals(value) != true)) {
                    this.HaveDependentsField = value;
                    this.RaisePropertyChanged("HaveDependents");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public string HomePhone {
            get {
                return this.HomePhoneField;
            }
            set {
                if ((object.ReferenceEquals(this.HomePhoneField, value) != true)) {
                    this.HomePhoneField = value;
                    this.RaisePropertyChanged("HomePhone");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public PulseLeads.ConsoleTest.PulseLeadServiceClient.Housing_Status HousingStatus {
            get {
                return this.HousingStatusField;
            }
            set {
                if ((this.HousingStatusField.Equals(value) != true)) {
                    this.HousingStatusField = value;
                    this.RaisePropertyChanged("HousingStatus");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public bool IncludeEscrows {
            get {
                return this.IncludeEscrowsField;
            }
            set {
                if ((this.IncludeEscrowsField.Equals(value) != true)) {
                    this.IncludeEscrowsField = value;
                    this.RaisePropertyChanged("IncludeEscrows");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public bool InterestOnly {
            get {
                return this.InterestOnlyField;
            }
            set {
                if ((this.InterestOnlyField.Equals(value) != true)) {
                    this.InterestOnlyField = value;
                    this.RaisePropertyChanged("InterestOnly");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public string LeadId {
            get {
                return this.LeadIdField;
            }
            set {
                if ((object.ReferenceEquals(this.LeadIdField, value) != true)) {
                    this.LeadIdField = value;
                    this.RaisePropertyChanged("LeadId");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public string LeadSource {
            get {
                return this.LeadSourceField;
            }
            set {
                if ((object.ReferenceEquals(this.LeadSourceField, value) != true)) {
                    this.LeadSourceField = value;
                    this.RaisePropertyChanged("LeadSource");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public PulseLeads.ConsoleTest.PulseLeadServiceClient.LiquidAssets[] LiquidAssets {
            get {
                return this.LiquidAssetsField;
            }
            set {
                if ((object.ReferenceEquals(this.LiquidAssetsField, value) != true)) {
                    this.LiquidAssetsField = value;
                    this.RaisePropertyChanged("LiquidAssets");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public int LoanAmount {
            get {
                return this.LoanAmountField;
            }
            set {
                if ((this.LoanAmountField.Equals(value) != true)) {
                    this.LoanAmountField = value;
                    this.RaisePropertyChanged("LoanAmount");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public string LoanOfficerFirstName {
            get {
                return this.LoanOfficerFirstNameField;
            }
            set {
                if ((object.ReferenceEquals(this.LoanOfficerFirstNameField, value) != true)) {
                    this.LoanOfficerFirstNameField = value;
                    this.RaisePropertyChanged("LoanOfficerFirstName");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public string LoanOfficerLastName {
            get {
                return this.LoanOfficerLastNameField;
            }
            set {
                if ((object.ReferenceEquals(this.LoanOfficerLastNameField, value) != true)) {
                    this.LoanOfficerLastNameField = value;
                    this.RaisePropertyChanged("LoanOfficerLastName");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public string LoanProgram {
            get {
                return this.LoanProgramField;
            }
            set {
                if ((object.ReferenceEquals(this.LoanProgramField, value) != true)) {
                    this.LoanProgramField = value;
                    this.RaisePropertyChanged("LoanProgram");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public string LoanType {
            get {
                return this.LoanTypeField;
            }
            set {
                if ((object.ReferenceEquals(this.LoanTypeField, value) != true)) {
                    this.LoanTypeField = value;
                    this.RaisePropertyChanged("LoanType");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public PulseLeads.ConsoleTest.PulseLeadServiceClient.Address MailingAddress {
            get {
                return this.MailingAddressField;
            }
            set {
                if ((object.ReferenceEquals(this.MailingAddressField, value) != true)) {
                    this.MailingAddressField = value;
                    this.RaisePropertyChanged("MailingAddress");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public decimal MonthlyPayment {
            get {
                return this.MonthlyPaymentField;
            }
            set {
                if ((this.MonthlyPaymentField.Equals(value) != true)) {
                    this.MonthlyPaymentField = value;
                    this.RaisePropertyChanged("MonthlyPayment");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public string Notes {
            get {
                return this.NotesField;
            }
            set {
                if ((object.ReferenceEquals(this.NotesField, value) != true)) {
                    this.NotesField = value;
                    this.RaisePropertyChanged("Notes");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public PulseLeads.ConsoleTest.PulseLeadServiceClient.OccupancyType OccupancyType {
            get {
                return this.OccupancyTypeField;
            }
            set {
                if ((this.OccupancyTypeField.Equals(value) != true)) {
                    this.OccupancyTypeField = value;
                    this.RaisePropertyChanged("OccupancyType");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public PulseLeads.ConsoleTest.PulseLeadServiceClient.OtherIncome[] OtherIncome {
            get {
                return this.OtherIncomeField;
            }
            set {
                if ((object.ReferenceEquals(this.OtherIncomeField, value) != true)) {
                    this.OtherIncomeField = value;
                    this.RaisePropertyChanged("OtherIncome");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public PulseLeads.ConsoleTest.PulseLeadServiceClient.PreferredContactMethod PreferredContactMethod {
            get {
                return this.PreferredContactMethodField;
            }
            set {
                if ((this.PreferredContactMethodField.Equals(value) != true)) {
                    this.PreferredContactMethodField = value;
                    this.RaisePropertyChanged("PreferredContactMethod");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public PulseLeads.ConsoleTest.PulseLeadServiceClient.Address Property {
            get {
                return this.PropertyField;
            }
            set {
                if ((object.ReferenceEquals(this.PropertyField, value) != true)) {
                    this.PropertyField = value;
                    this.RaisePropertyChanged("Property");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public string PropertyType {
            get {
                return this.PropertyTypeField;
            }
            set {
                if ((object.ReferenceEquals(this.PropertyTypeField, value) != true)) {
                    this.PropertyTypeField = value;
                    this.RaisePropertyChanged("PropertyType");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public int PropertyValue {
            get {
                return this.PropertyValueField;
            }
            set {
                if ((this.PropertyValueField.Equals(value) != true)) {
                    this.PropertyValueField = value;
                    this.RaisePropertyChanged("PropertyValue");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public PulseLeads.ConsoleTest.PulseLeadServiceClient.PurposeOfLoan PurposeOfLoan {
            get {
                return this.PurposeOfLoanField;
            }
            set {
                if ((this.PurposeOfLoanField.Equals(value) != true)) {
                    this.PurposeOfLoanField = value;
                    this.RaisePropertyChanged("PurposeOfLoan");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public decimal Rate {
            get {
                return this.RateField;
            }
            set {
                if ((this.RateField.Equals(value) != true)) {
                    this.RateField = value;
                    this.RaisePropertyChanged("Rate");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public int RentAmount {
            get {
                return this.RentAmountField;
            }
            set {
                if ((this.RentAmountField.Equals(value) != true)) {
                    this.RentAmountField = value;
                    this.RaisePropertyChanged("RentAmount");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute(IsRequired=true)]
        public PulseLeads.ConsoleTest.PulseLeadServiceClient.ReqHdr RequestHeader {
            get {
                return this.RequestHeaderField;
            }
            set {
                if ((object.ReferenceEquals(this.RequestHeaderField, value) != true)) {
                    this.RequestHeaderField = value;
                    this.RaisePropertyChanged("RequestHeader");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public string SSN {
            get {
                return this.SSNField;
            }
            set {
                if ((object.ReferenceEquals(this.SSNField, value) != true)) {
                    this.SSNField = value;
                    this.RaisePropertyChanged("SSN");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public int Term {
            get {
                return this.TermField;
            }
            set {
                if ((this.TermField.Equals(value) != true)) {
                    this.TermField = value;
                    this.RaisePropertyChanged("Term");
                }
            }
        }
        
        public event System.ComponentModel.PropertyChangedEventHandler PropertyChanged;
        
        protected void RaisePropertyChanged(string propertyName) {
            System.ComponentModel.PropertyChangedEventHandler propertyChanged = this.PropertyChanged;
            if ((propertyChanged != null)) {
                propertyChanged(this, new System.ComponentModel.PropertyChangedEventArgs(propertyName));
            }
        }
    }
    
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ServiceModel.ServiceContractAttribute(ConfigurationName="PulseLeadServiceClient.IPulseLeadService")]
    public interface IPulseLeadService {
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IPulseLeadService/PostLead", ReplyAction="http://tempuri.org/IPulseLeadService/PostLeadResponse")]
        PulseLeads.ConsoleTest.PulseLeadServiceClient.RespHdr PostLead(PulseLeads.ConsoleTest.PulseLeadServiceClient.PostLeadRequest req);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IPulseLeadService/PostLoanApp", ReplyAction="http://tempuri.org/IPulseLeadService/PostLoanAppResponse")]
        PulseLeads.ConsoleTest.PulseLeadServiceClient.RespHdr PostLoanApp(PulseLeads.ConsoleTest.PulseLeadServiceClient.PostLoanAppRequest req);
    }
    
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    public interface IPulseLeadServiceChannel : PulseLeads.ConsoleTest.PulseLeadServiceClient.IPulseLeadService, System.ServiceModel.IClientChannel {
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    public partial class PulseLeadServiceClient : System.ServiceModel.ClientBase<PulseLeads.ConsoleTest.PulseLeadServiceClient.IPulseLeadService>, PulseLeads.ConsoleTest.PulseLeadServiceClient.IPulseLeadService {
        
        public PulseLeadServiceClient() {
        }
        
        public PulseLeadServiceClient(string endpointConfigurationName) : 
                base(endpointConfigurationName) {
        }
        
        public PulseLeadServiceClient(string endpointConfigurationName, string remoteAddress) : 
                base(endpointConfigurationName, remoteAddress) {
        }
        
        public PulseLeadServiceClient(string endpointConfigurationName, System.ServiceModel.EndpointAddress remoteAddress) : 
                base(endpointConfigurationName, remoteAddress) {
        }
        
        public PulseLeadServiceClient(System.ServiceModel.Channels.Binding binding, System.ServiceModel.EndpointAddress remoteAddress) : 
                base(binding, remoteAddress) {
        }
        
        public PulseLeads.ConsoleTest.PulseLeadServiceClient.RespHdr PostLead(PulseLeads.ConsoleTest.PulseLeadServiceClient.PostLeadRequest req) {
            return base.Channel.PostLead(req);
        }
        
        public PulseLeads.ConsoleTest.PulseLeadServiceClient.RespHdr PostLoanApp(PulseLeads.ConsoleTest.PulseLeadServiceClient.PostLoanAppRequest req) {
            return base.Channel.PostLoanApp(req);
        }
    }
}
